### ISSUE TITLE
Synchronized with 4.5.13?

### ISSUE THREAD

**Issue by nathanchance** [OnePlusOSS/android_vendor_qcom-opensource_wlan_qcacld-3.0#1]
There have been a couple of updates since this was updated on August 4th that mention Wi-Fi connectivity improvements. Are this repo and the other two ([android_vendor_qcom-opensource_wlan_qca-wifi-host-cmn](https://github.com/OnePlusOSS/android_vendor_qcom-opensource_wlan_qca-wifi-host-cmn) and [android_vendor_qcom-opensource_wlan_fw-api](https://github.com/OnePlusOSS/android_vendor_qcom-opensource_wlan_fw-api)) up to date with those changes? If not, would you consider pushing them so custom kernels can inline the module without needing to hack loading the prebuilt one?

Much appreciated! @aaronqiuchiu

**Comment by brucechiu1113** [comment]
@nathanchance 

1. We improved Wi-Fi connectivity by fixing bugs in Wi-Fi firmware, not driver. 
2. We don't have plan to move these repositories to kernel. The developers could merge them with Qualcomm CAF's driver easily with the original layout. The baseline we used is LA.UM.5.7.r1-0XXXX-8x98.0, you could refer to CAF: https://wiki.codeaurora.org/xwiki/bin/QAEP/release

Thanks,
Bruce

**Comment by nathanchance** [comment]
@brucechiu1113 thank you for the response! Any time I try to update the driver from CAF, I experience a notification delay. It's incredibly bizarre so I figured maybe there was something that was missing from this repository so I appreciate the clarification.

**Comment by hypermagik** [comment]
@nathanchance I think the problem lies in core/hdd/inc/wlan_hdd_packet_filter_rules.h. The compare flag for L2 is set to 3 (non-equality), so the filters never actually match the IP/IPv6 ethertypes. Changing the flags to 1 (equality) appears to do the trick:
[...] [...]@0 R0: [soft_irq][...] [...]  wlan: [0:F :WMA] WLAN triggered wakeup: PACKET_FILTER_MATCH (34), vdev: 0 (STA)

Also, filters in the wlan.ko from OnePlus differ from the ones defined in wlan_hdd_packet_filter_rules.h (the second filter also blocks broadcasts), so this is not the exact same code they used to build the driver...

**Comment by nathanchance** [comment]
@HypermagiK is this the case on Oreo as well? The delay issue is still present. I'm almost wondering if this is a result of discrepancies between the AOSP and kernel builds of qcacld-3.0. 

I also should have closed this issue a while ago lol.

**Comment by hypermagik** [comment]
@nathanchance I believe this is only the case for Oreo, sorry for not being very clear. On the QC8998_N_7.1 branch, the L2 part of the filter is commented out.
